on:
 push

jobs:
 update:
  runs-on: ubuntu-latest

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.0-alpha.4

    - name: Install Databricks CLI
      run: |
        python -m pip install --upgrade databricks-cli

    - name: Remote update Prod Repo
      run: databricks repos update --branch main "/Repos/sara.hovakeemian@databricks.com/demo_repo"
      working-directory: .
      env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
